export const SET_CURRENT_VALUE = "SET_CURRENT_VALUE";
export const SET_PREVIOUS_VALUE = "SET_PREVIOUS_VALUE";
export const SET_IS_PREVIOUS_RESULT = "SET_IS_PREVIOUS_RESULT";
export const SET_OPERATION = "SET_OPERATION";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
